#!/usr/bin/env python3
"""
NTC Thermistor Lookup Table Generator
======================================
Generates a C header file containing an ADC-to-temperature lookup table for an
NTC (Negative Temperature Coefficient) thermistor.

The thermistor is assumed to be in a voltage-divider circuit:

    VCC
     |
    Rpullup
     |
     +--- ADC pin
     |
    NTC (thermistor)
     |
    GND

Temperature is computed using the Beta parameter equation:

    1/T = 1/T25 + (1/Beta) * ln(R_ntc / R25)

where T is in Kelvin.

Usage
-----
    python3 ntc_table_converter.py [options]

Options
-------
    -r, --r25       NTC resistance at 25 °C in Ohms (default: 10000)
    -b, --beta      Beta coefficient in Kelvin (default: 3950)
    -p, --pullup    Pull-up resistor value in Ohms (default: 10000)
    -a, --adc-bits  ADC resolution in bits (default: 12)
    --t-min         Minimum temperature in °C to represent (default: -40)
    --t-max         Maximum temperature in °C to represent (default: 125)
    -o, --output    Output header file path (default: ../firmware/ntc_table.h)
    --no-header     Suppress the auto-generated C header file output

Example
-------
    # Generate with default parameters (10 kΩ NTC, Beta=3950, 10 kΩ pull-up, 12-bit ADC)
    python3 ntc_table_converter.py

    # Custom NTC: 100 kΩ, Beta=4100, 100 kΩ pull-up
    python3 ntc_table_converter.py -r 100000 -b 4100 -p 100000
"""

import argparse
import math
import os
import sys
from datetime import datetime, timezone


def adc_to_resistance(adc_value, adc_max, r_pullup):
    """Convert an ADC reading to NTC resistance (voltage-divider, pull-up config).

    V_adc = VCC * R_ntc / (R_pullup + R_ntc)
    ADC   = adc_max * R_ntc / (R_pullup + R_ntc)
    => R_ntc = ADC * R_pullup / (adc_max - ADC)

    Edge cases:
      ADC = 0       → R_ntc = 0 Ω  (NTC short-circuit, very high temperature)
      ADC = adc_max → R_ntc = ∞ Ω  (NTC open-circuit, very low temperature)
    """
    if adc_value == 0:
        return 0.0
    if adc_value >= adc_max:
        return float("inf")
    return adc_value * r_pullup / (adc_max - adc_value)


def resistance_to_temperature(r_ntc, r25, beta):
    """Convert NTC resistance to temperature in °C using the Beta equation."""
    T25 = 25.0 + 273.15  # 25 °C in Kelvin
    if r_ntc <= 0:
        return float("inf")   # short circuit → very high temperature
    if r_ntc == float("inf"):
        return float("-inf")  # open circuit → very low temperature
    inv_T = 1.0 / T25 + (1.0 / beta) * math.log(r_ntc / r25)
    T_kelvin = 1.0 / inv_T
    return T_kelvin - 273.15


def generate_table(r25, beta, r_pullup, adc_bits, t_min, t_max):
    """Generate a list of (adc_value, temperature_c) tuples for all ADC values.

    ADC values that map to temperatures outside [t_min, t_max] are clamped to
    the nearest bound so that the firmware can always produce a valid reading.
    """
    adc_max = (1 << adc_bits) - 1  # e.g. 4095 for 12-bit
    table = []
    for adc in range(adc_max + 1):
        r = adc_to_resistance(adc, adc_max, r_pullup)
        temp_c = resistance_to_temperature(r, r25, beta)
        # Clamp to representable range
        temp_c = max(t_min, min(t_max, temp_c))
        # Store as tenths of a degree (int16_t) to keep precision without floats
        table.append(int(round(temp_c * 10)))
    return table


def write_header(table, r25, beta, r_pullup, adc_bits, t_min, t_max, output_path):
    """Write the lookup table to a C header file."""
    adc_max = (1 << adc_bits) - 1
    num_entries = len(table)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "/* ntc_table.h — Auto-generated by tools/ntc_table_converter.py",
        f" * Generated : {timestamp}",
        f" * NTC R25   : {r25} Ω",
        f" * Beta      : {beta} K",
        f" * Pull-up   : {r_pullup} Ω",
        f" * ADC bits  : {adc_bits} ({adc_max + 1} entries, index = ADC value)",
        f" * Temp range: {t_min} °C to {t_max} °C",
        " * Units     : tenths of a degree Celsius (divide by 10 to get °C)",
        " * Circuit   : VCC — Rpullup — ADC — NTC — GND",
        " */",
        "",
        "#ifndef NTC_TABLE_H",
        "#define NTC_TABLE_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define NTC_ADC_BITS   {adc_bits}",
        f"#define NTC_ADC_MAX    {adc_max}",
        f"#define NTC_R25        {r25}U",
        f"#define NTC_BETA       {beta}U",
        f"#define NTC_PULLUP     {r_pullup}U",
        f"#define NTC_TEMP_MIN   {t_min * 10}  /* {t_min} °C in tenths */",
        f"#define NTC_TEMP_MAX   {t_max * 10}  /* {t_max} °C in tenths */",
        "",
        "/* ntc_table[adc_value] → temperature in tenths of °C",
        " * Example: ntc_table[2048] = 250  →  25.0 °C",
        " */",
        f"static const int16_t ntc_table[{num_entries}] = {{",
    ]

    # Write 8 values per line for readability
    values_per_line = 8
    for i in range(0, num_entries, values_per_line):
        chunk = table[i : i + values_per_line]
        formatted = ", ".join(f"{v:6d}" for v in chunk)
        comma = "," if (i + values_per_line) < num_entries else ""
        lines.append(f"    {formatted}{comma}")

    lines += [
        "};",
        "",
        "/**",
        " * @brief  Look up temperature from a raw ADC reading.",
        " * @param  adc_value  Raw ADC value (0 … NTC_ADC_MAX).",
        " * @return Temperature in tenths of °C (divide by 10 for °C).",
        " */",
        "static inline int16_t ntc_adc_to_temp(uint16_t adc_value) {",
        "    if (adc_value > NTC_ADC_MAX) {",
        "        adc_value = NTC_ADC_MAX;",
        "    }",
        "    return ntc_table[adc_value];",
        "}",
        "",
        "#endif /* NTC_TABLE_H */",
        "",
    ]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {num_entries}-entry NTC lookup table → {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate an NTC thermistor ADC-to-temperature lookup table as a C header."
    )
    parser.add_argument(
        "-r", "--r25",
        type=float,
        default=10000,
        metavar="OHMS",
        help="NTC resistance at 25 °C in Ohms (default: 10000)",
    )
    parser.add_argument(
        "-b", "--beta",
        type=float,
        default=3950,
        metavar="K",
        help="Beta coefficient in Kelvin (default: 3950)",
    )
    parser.add_argument(
        "-p", "--pullup",
        type=float,
        default=10000,
        metavar="OHMS",
        help="Pull-up resistor value in Ohms (default: 10000)",
    )
    parser.add_argument(
        "-a", "--adc-bits",
        type=int,
        default=12,
        metavar="BITS",
        help="ADC resolution in bits (default: 12)",
    )
    parser.add_argument(
        "--t-min",
        type=int,
        default=-40,
        metavar="CELSIUS",
        help="Minimum representable temperature in °C (default: -40)",
    )
    parser.add_argument(
        "--t-max",
        type=int,
        default=125,
        metavar="CELSIUS",
        help="Maximum representable temperature in °C (default: 125)",
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=None,
        help=(
            "Output header file path "
            "(default: firmware/ntc_table.h relative to the repository root)"
        ),
    )

    args = parser.parse_args()

    if args.output is None:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        args.output = os.path.join(script_dir, "..", "firmware", "ntc_table.h")

    if args.r25 <= 0:
        print("Error: --r25 must be a positive value.", file=sys.stderr)
        sys.exit(1)
    if args.beta <= 0:
        print("Error: --beta must be a positive value.", file=sys.stderr)
        sys.exit(1)
    if args.pullup <= 0:
        print("Error: --pullup must be a positive value.", file=sys.stderr)
        sys.exit(1)
    if args.adc_bits < 1 or args.adc_bits > 16:
        print("Error: --adc-bits must be between 1 and 16.", file=sys.stderr)
        sys.exit(1)
    if args.t_min >= args.t_max:
        print("Error: --t-min must be less than --t-max.", file=sys.stderr)
        sys.exit(1)

    table = generate_table(
        r25=args.r25,
        beta=args.beta,
        r_pullup=args.pullup,
        adc_bits=args.adc_bits,
        t_min=args.t_min,
        t_max=args.t_max,
    )
    write_header(
        table=table,
        r25=int(args.r25),
        beta=int(args.beta),
        r_pullup=int(args.pullup),
        adc_bits=args.adc_bits,
        t_min=args.t_min,
        t_max=args.t_max,
        output_path=args.output,
    )


if __name__ == "__main__":
    main()
